version: 2

registries:
  github-maven:
    type: maven-repository
    url: https://maven.pkg.github.com
    username: ${{ secrets.USER }}
    password: ${{ secrets.GHP }}

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/"
    registries: "*"
    schedule:
      interval: "daily"
    groups:
      ads:
        patterns:
          - "com.adsbynimbus*"
          - "com.amazon*"
          - "*play-services-ads"
          - "*ads-mobile-sdk"
          - "com.iabtcf*"
# Only update Android Gradle Plugin patches to maintain compatibility with JetBrains IDEA
      android-gradle:
        patterns:
          - "com.android.*"
        update-types:
          - "patch"
      compose:
        patterns:
          - "org.jetbrains.compose"
          - "androidx.compose*"
          - "*-compose" # Covers activity-compose and navigation-compose
      androidx:
        patterns:
          - "androidx.*"
      kotlin:
        patterns:
          - "org.jetbrains.*"
      admanager-api:
        patterns:
          - "com.google.api*"
          - "com.google.auth*"
          - "com.fasterxml*"
          - "*gson"
          - "*commons*"
      networking:
        patterns:
          - "com.squareup*"
      other:
        patterns:
          - "*"
    ignore:
      - dependency-name: "com.android.*"
        update-types: [ "version-update:semver-minor", "version-update:semver-major" ]
