name: AdMob Extensions

on:
  push:
    tags:
      - 'admob/**'

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Publish AdMob Extensions SDK
    runs-on: ubuntu-latest
    if: github.repository == 'adsbynimbus/solutions'
    env:
      ORG_GRADLE_PROJECT_githubUsername: ${{ github.actor }}
      ORG_GRADLE_PROJECT_githubPassword: ${{ github.token }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6
      - name: Set Version from Tag Name
        id: tag_name
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/admob\//}" >> $GITHUB_OUTPUT
      - name: Publish
        uses: ./.github/actions/gradle
        env:
          ORG_GRADLE_PROJECT_version: ${{ steps.tag_name.outputs.VERSION }}
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
          task: :sdk-extensions:android:admob:publish
