name: AdMob Extensions

on:
  push:
    tags:
      - 'admob/**'

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Publish AdMob Extensions SDK
    runs-on: ubuntu-latest
    env:
      ORG_GRADLE_PROJECT_githubUsername: ${{ github.actor }}
      ORG_GRADLE_PROJECT_githubPassword: ${{ github.token }}
      ORG_GRADLE_PROJECT_openrtbUsername: ${{ github.actor }}
      ORG_GRADLE_PROJECT_openrtbPassword: ${{ github.token }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '24'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
      - name: Set Version from Tag Name
        id: tag_name
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/admob\//}" >> $GITHUB_OUTPUT
      - name: Publish
        if: github.repository == 'adsbynimbus/solutions'
        env:
          ORG_GRADLE_PROJECT_version: ${{ steps.tag_name.outputs.VERSION }}
        run: ./gradlew :sdk-extensions:android:admob:publish
