name: AdMob Extensions

on:
  push:
    tags:
      - 'admob/**'
      - 'admob-nextgen/**'

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Publish AdMob Extensions SDK
    runs-on: ubuntu-latest
    if: github.repository == 'adsbynimbus/solutions'
    env:
      ORG_GRADLE_PROJECT_githubUsername: ${{ github.actor }}
      ORG_GRADLE_PROJECT_githubPassword: ${{ github.token }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6
      - name: Setup Gradle
        uses: ./.github/actions/gradle
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
      - name: Set Version and Command from Tag Name
        id: tag_name
        run: |
          echo VERSION=`echo ${{ github.ref }} | sed 's@.*/@@'` >> $GITHUB_OUTPUT
          echo PROJECT=`echo ${{ github.ref }} | sed -E 's|.*/([^/]*)/.*|\1|'` >> $GITHUB_OUTPUT
      - name: Publish
        env:
          ORG_GRADLE_PROJECT_version: ${{ steps.tag_name.outputs.VERSION }}
        run: ./gradlew :sdk-extensions:android:${{ steps.tag_name.outputs.PROJECT }}:publish
